-- Seed data for N9N Backend
-- This file can be executed directly in PostgreSQL

-- Insert or update demo tenant (UPSERT)
INSERT INTO tenants (id, name, email, "isActive", "createdAt", "updatedAt")
VALUES (
  'demo-tenant',
  'Demo Tenant',
  'demo@n9n.com',
  true,
  NOW(),
  NOW()
)
ON CONFLICT (email) DO UPDATE SET
  name = EXCLUDED.name,
  "isActive" = EXCLUDED."isActive",
  "updatedAt" = NOW();

-- Insert sample workflow
-- Note: The workflow ID will be auto-generated by PostgreSQL
INSERT INTO workflows (id, "tenantId", name, description, nodes, edges, "isActive", "createdAt", "updatedAt")
VALUES (
  gen_random_uuid(),
  'demo-tenant',
  'Welcome Flow',
  'Simple welcome message flow',
  '[
    {
      "id": "trigger-1",
      "type": "TRIGGER_MESSAGE",
      "config": {
        "pattern": "hello",
        "matchType": "contains"
      },
      "position": { "x": 250, "y": 0 }
    },
    {
      "id": "send-1",
      "type": "SEND_MESSAGE",
      "config": {
        "message": "Hello! Welcome to N9N. What is your name?"
      },
      "position": { "x": 250, "y": 100 }
    },
    {
      "id": "wait-1",
      "type": "WAIT_REPLY",
      "config": {
        "saveAs": "userName",
        "timeoutSeconds": 300,
        "onTimeout": "END"
      },
      "position": { "x": 250, "y": 200 }
    },
    {
      "id": "send-2",
      "type": "SEND_MESSAGE",
      "config": {
        "message": "Nice to meet you, {{variables.userName}}! 👋"
      },
      "position": { "x": 250, "y": 300 }
    },
    {
      "id": "end-1",
      "type": "END",
      "config": {
        "outputVariables": ["userName"]
      },
      "position": { "x": 250, "y": 400 }
    }
  ]'::jsonb,
  '[
    {
      "id": "edge-1",
      "source": "trigger-1",
      "target": "send-1"
    },
    {
      "id": "edge-2",
      "source": "send-1",
      "target": "wait-1"
    },
    {
      "id": "edge-3",
      "source": "wait-1",
      "target": "send-2"
    },
    {
      "id": "edge-4",
      "source": "send-2",
      "target": "end-1"
    }
  ]'::jsonb,
  false,
  NOW(),
  NOW()
);

